version: "3.9"

services:
  whisper-api:
    build: ML_API
    container_name: whisper-api
    restart: unless-stopped
    ports:
      - "8000:8000"

  tg-bot:
    build: ./bot
    container_name: tg-bot
    env_file:
      - .env
    depends_on:
      - whisper-api
    restart: unless-stopped
